server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location = ${URL_PREFIX}/download-metadata.json {
        alias /usr/share/nginx/html/download-metadata.json;
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=3600";
    }

    # Python tarballs
    location ${URL_PREFIX}/assets/ {
        alias /usr/share/nginx/html/assets/;
        autoindex off;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=86400";
    }

    # Health check
    location = ${URL_PREFIX}/health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
