name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [uv-oasis]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --locked --all-packages

      - name: Check Format
        run: uv run ruff format --check packages/${{ matrix.package }}/

      - name: Lint
        run: uv run ruff check packages/${{ matrix.package }}/

      - name: Check Type
        run: uv run ty check --project packages/${{ matrix.package }}

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [uv-oasis]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --locked --all-packages

      - name: Run Pytest with Coverage
        run: uv run --package ${{ matrix.package }} pytest --cov --cov-branch --cov-report=xml packages/${{ matrix.package }}/tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
